Prometheus Helm Chart
filetrust/icap-infrastructure pull request #496
Opened 2021-01-15 09:37 UTC by shashanksinha89

2021-01-15 09:56 UTC, MattCavey commented
Adding @gargath as reviewer so Codurance gets visibility of the helm charts

2021-01-15 11:49 UTC, mpigram approved these changes
I can't see anything out of place, all looks good to me! I'll await @gargath review though as I may have missed something :)

2021-01-15 13:44 UTC, gargath requested changes
These charts don't seem to have been adapted to work with the Rancher-based setup.
To do so, each container image reference needs to template an additional registry component.

Each `values.yaml` MUST list images in an `imagestore` stanza and contain the three components `registry`, `repository` and `tag`.

Services must use type `NodePort` and also be included in existing load balancer rules to be available on Rancher.
Any such port mapping needs to be cleared with @BigPeeg to ensure compliance with the SoW.

2021-01-15 13:44 UTC, gargath commented on helm-charts/grafana/values.yaml
> +  loadBalancerSourceRanges:
What are these hard-coded IPs?

2021-01-15 13:44 UTC, gargath commented on helm-charts/grafana/values.yaml
> +  type: LoadBalancer
Services of type `LoadBalancer` are not available on Rancher.
`NodePort` in conjunction with existing load balancer rules need to be used.

2021-01-15 13:44 UTC, gargath commented on helm-charts/grafana/values.yaml
> +  existingSecret: ""
How is this meant to work?
Is an existing secret prerequisite? If so, how does it get to the cluster?

2021-01-15 14:45 UTC, himanshu2464 commented on helm-charts/grafana/values.yaml
> +  existingSecret: ""
yes, we can change it when we deploy it with our username and password when you deploy the grafana using helm it will give you instructions to get the password to login to grafana .

this will override the default user and password of the grafana .

2021-01-15 15:17 UTC, himanshu2464 commented on helm-charts/grafana/values.yaml
> +  type: LoadBalancer
we can expose the service with nodePort as well it's dynamic according to the environment.

2021-01-15 15:21 UTC, himanshu2464 commented on helm-charts/grafana/values.yaml
> +  loadBalancerSourceRanges:
These subnets are of VPN so we need grafana to be view within VPN. so we have added this IP and we can also add another subnet as well it's depending on our need which network we wanted to allow access to view our grafana dashboards.

2021-01-15 15:34 UTC, gargath commented on helm-charts/grafana/values.yaml
> +  loadBalancerSourceRanges:
Might be worth a comment indicating where these are taken from.

2021-01-18 09:28 UTC, gargath commented
The references to the container images in `values.yaml` need to match exactly the structure in the existing charts (e.g. https://github.com/filetrust/icap-infrastructure/blob/f2699f6c0c42d4f6dd47f1f42142a35375eebf9a/adaptation/values.yaml#L117-L157) in order to allow us to copy required images from public registries to ACR.

Could I ask you to refactor this to match this structure
```
imagestore:
  service-1:
    registry: ""
    repository: glasswallsolutions/some-service
    tag: some-tag
  service-2:
    [...]
```

2021-01-18 18:04 UTC, gargath approved these changes
That's looking good now.
Let's get it merged and take it for a spin as soon as we can.

2021-01-19 13:13 UTC, merged